export const graphicsDirectory = "/graphics";
export const mapKey = import.meta.env.VITE_MAPBOX_KEY;
export const mapStyle = import.meta.env.VITE_MAPBOX_STYLE;
export const travelEndpoint = import.meta.env.VITE_TRAVEL_ENDPOINT;
export const unsplashClientId = import.meta.env.VITE_UNSPLASH_CLIENT_ID;
export const unsplashBaseUrl = "https://api.unsplash.com";
export const environment = import.meta.env.VITE_ENV;
export const GDPRCookie = "gdprConsent"
export const hotjarSiteId = import.meta.env.VITE_HOTJAR_ID ?? "";
export const hotjarVersion = 6;