name: Build Docker Image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0' # or whichever version you're targeting

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build . -t wander-by-way-front:latest

      - name: Run Docker image
        run: docker run -d -p 8080:80 wander-by-way-front:latest